### ISSUE TITLE
Error "Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type"

### ISSUE THREAD

**Issue by rov-co** [aws-solutions/aws-waf-security-automations#112]
Deploying this solution in Sydney region fails with following error message: "Failed to create resource. An error occurred (WAFStaleDataException) when calling the UpdateWebACL operation: The input token is no longer current.".
Error "Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type"

After investigating found that we need to use a new S3 Bucket - Please update the solution to indicate customer should use an new S3 bucket

**Comment by aijunpeng** [comment]
Existing bucket is now supported. closing the issue.
