### ISSUE TITLE
WAF set hours base rule and set custom message if Ip will block by waf rule

### ISSUE THREAD

**Issue by bipingagan** [aws-solutions/aws-waf-security-automations#122]
Hello Team,

Can anyone help to setup WAF HTTP Flood Rule in hours base, I have setup WAF for my ELB and in config I am able to set Flood base rule count request in 5 min can we increase time 5 to 1 hours ?

2. We also looking set custom message show if ip will block by rule, currently  it showing 503, I got option to set custom message on cloudfrunt but I want to set et on ELB base rule

**Comment by dscpinheiro** [comment]
Hi @bipingagan,

Sorry for the delay in the response.

1. WAF Classic does not support changing the period length from 5 minutes at this time.

2. It doesn't look like it's possible to set a custom message on the rule. As you mentioned, the alternative is to use CloudFront error pages (https://docs.aws.amazon.com/waf/latest/developerguide/classic-cloudfront-features.html#classic-cloudfront-features-custom-error-pages)

**Comment by bipingagan** [comment]
Hello @dscpinheiro 

Thanks for your response,

"WAF Classic does not support changing the period length from 5 minutes at this time."

Can we do it any other way on aws ?

Thanks

**Comment by dscpinheiro** [comment]
Hi @bipingagan,

Unfortunately there isn't. API Gateway does have throttling capabilities (https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html), but it's measured in RPS (requests per second), and if you're not using it already it'd require some architectural changes.
