### ISSUE TITLE
Replace use of whitelist with allowlist and blacklist with denylist

### ISSUE THREAD

**Issue by hemedga** [aws-solutions/aws-waf-security-automations#131]
Per https://twitter.com/andrestaltz/status/1030200563802230786.

I'm for replacing the terms in the template and documentation.

**Comment by rakshb** [comment]
Thanks @hemedga. We will review and update this in an upcoming release

**Comment by rakshb** [comment]
Thanks @hemedga. We will review this and add to our backlog

**Comment by GeorgeTailor** [comment]
I identify myself of 'list' race and my gender is 'allow' and I find this offensive!

**Comment by maykays** [comment]
@hemedga Thank you for bringing this to our attention. We will include these changes in the next release.

**Comment by aijunpeng** [comment]
Updates have already been applied. closing this issue
