### ISSUE TITLE
IAM Permission boundary

### ISSUE THREAD

**Issue by pkennedyvt** [aws-solutions/aws-waf-security-automations#139]
**Is your feature request related to a problem? Please describe.**
It would be nice to add a parameter for an IAM Permission boundary for the role creations

**Describe the feature you'd like**
Some organizations leverage permission boundaries, and if this were parameterized they could still use the public repo without having to build their own.  I believe there were 6 places in the main template and one in the web-acl template where I added:
PermissionsBoundary: "arn:aws:iam::123456789012/policy/mypolicyname'

**Additional context**

**Comment by aijunpeng** [comment]
Thanks for the comment. We have added your request to our solution backlog items and it will be considered in future
solution releases.

**Comment by rakshb** [comment]
There is a PR for this request created (#176). We will review the PR and prioritize for a future release. Closing this as a duplicate.
