### ISSUE TITLE
Dashboard broken

### ISSUE THREAD

**Issue by peteroruba** [aws-solutions/aws-waf-security-automations#145]
**Describe the bug**
The CloudWatch Dashboard has references to metrics that do not exist. Basically a completely empty Dashboard with no graphs at all.

**To Reproduce**
Deployment of the solution with HTTP Flood protection based on WAF and Honeypot feature enabled.

**Expected behavior**
A CloudWatch dashboard showing WAF metrics

**Please complete the following information about the solution:**
- [ ] Version: v3.0.0

- [ ] Region: eu-central-1 and us-east-1
- [ ] Was the solution modified from the version published on this repository?  No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? -
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Not applicable
- [ ] Were there any errors in the CloudWatch Logs? Not applicable

**Additional context**
The dashboard deployed with this solution shows no graphs. The metrics as show in "source" refer to metrics from namespace "WAF" while "AWS/WAFV2" would be the correct namespace. Also the nested stack's export "WAFWebACLMetricName" seems wrong.

**Comment by deolank** [comment]
Thanks for reporting this bug. We have added this to our backlog.

**Comment by aijunpeng** [comment]
This should be fixed in the latest version.
