### ISSUE TITLE
Eu-central-1 stack failed to create resource. An error occurred (ValidationException) when calling the UpdateWebACL operation: Cannot allow rule 76f7e440-41e5-4ae4-afae-8af7633aa5c5 with priority 10

### ISSUE THREAD

**Issue by kvranjith** [aws-solutions/aws-waf-security-automations#179]
Stack get failed to create /update the webacl in Frankfurt region.

"Failed to create resource. An error occurred (ValidationException) when calling the UpdateWebACL operation: Cannot allow rule 76f7e440-41e5-4ae4-afae-8af7633aa5c5 with priority 10. Another rule already has this priority."

Please advise to fix.
Regards,
K V Ranjith

**Comment by aijunpeng** [comment]
This seems a WAF service error. Can you check the rules for your webacl in AWS WAF Console and see if there is already a rule with the same priority?

**Comment by morjoan** [comment]
Please reopen if still an issue.
