### ISSUE TITLE
Ignore a certain uriList

### ISSUE THREAD

**Issue by joon73** [aws-solutions/aws-waf-security-automations#181]
**Is your feature request related to a problem? Please describe.**
Need to ignore a certain uriList. For example, /https* or a certain URI which can be ignored. Notice 'ignoredSufixes' can be configured through JSON, but not URIList.

**Describe the feature you'd like**
List of URIs that can be ignored for Scanner & Probe engine.
{"general": {"requestThreshold": 200, "blockPeriod": 300, "ignoredSufixes": []}, "ignoreduriList": [{}]}

**Comment by aijunpeng** [comment]
Thank you for the request. We have added your request to our backlog and it will be considered in future releases.

**Comment by rakshb** [comment]
Thanks for your request. The solution currently provides the ability to define a custom request threshold and block period for specific URIs. Please consider customizing the functionality for this specific use case.
