### ISSUE TITLE
Stack fails with Invalid scope - Template 3.1.0 - Cloudfront attach - Region EU (Frankfurt)

### ISSUE THREAD

**Issue by casper5822** [aws-solutions/aws-waf-security-automations#187]
Hello,
i just run the last template version with cloudfront resouce in EU (Frankfurt).
I gest an error on stack creation with "invalid scope".

How can i fix this? Is the template work in EU (Frankfurt) with cloudfront?

Thanks in advance.

Full error is:

`error reason: the scope is not valid., field: scope_value, parameter: cloudfront (service: wafv2, status code: 400, request id: f11107cd-44df-407e-aa70-f97e4270e35d, extended request id: null)`

**Comment by rakshb** [comment]
@casper5822 If you choose CLOUDFRONT as your endpoint, you must create your WAFV2 resources in the US
East (N. Virginia) Region, us-east-1.
