### ISSUE TITLE
Stack creation fails: "Error occurred while GetObject. S3 Error Code: NoSuchKey."

### ISSUE THREAD

**Issue by v-karbovnichy** [aws-solutions/aws-waf-security-automations#189]
**Describe the bug**
Stack creation fails with a error. See also #135 for the same error.
Logical ID: Helper
Status: CREATE_FAILED
Status reason : Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 39aab78e-c6e9-467e-b401-240e8bac28db; Proxy: null)

**To Reproduce**
Performed all the steps outlined in a Readme.

**Expected behavior**
Expected the Stack to be created successfully.

**Please complete the following information about the solution:**
- [x] Version: v1 (<-- I had set this version myself in the params, because I thought it was for my customizations versioning, not for this repo version) Originally checked out version 3.1.0 from the repo.
- [x] Region: us-east-1
- [x] Was the solution modified from the version published on this repository? YES
- [x] If the answer to the previous question was yes, are the changes available on GitHub? [fork+branch](https://github.com/v-karbovnichy/aws-waf-security-automations/tree/dnn)
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes, AWS Lambda have only one small function.
- [x] Were there any errors in the CloudWatch Logs? n/a

**Screenshots**
Will put in comments.

**Additional context**
Is reproducible 100% of the time.

**Comment by v-karbovnichy** [comment]
![image](https://user-images.githubusercontent.com/7301634/116591891-6ac8c900-a930-11eb-9e51-202c76c095be.png)

**Comment by v-karbovnichy** [comment]
![image](https://user-images.githubusercontent.com/7301634/116592082-a2d00c00-a930-11eb-9277-4341ac4769e4.png)

**Comment by v-karbovnichy** [comment]
![image](https://user-images.githubusercontent.com/7301634/116592170-bd09ea00-a930-11eb-9e0a-041841606d2d.png)

**Comment by v-karbovnichy** [comment]
![image](https://user-images.githubusercontent.com/7301634/116592250-dad74f00-a930-11eb-9918-af49a6e7fc3c.png)

**Comment by s-thom-lab** [comment]
Hello,

I am having the same error as well.

I am trying to use cdk codepipeline to build and deploy a serverless application(apigateway - lambda) using cdk. The pipeline is building correctly but errors out during deployment which creates the cloudformation template to create lambda and api gateway.

Error:
Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 6c84cebf-148d-41e6-9753-5ecd8c12b0d8; Proxy: null)

Please help me fix this issue. S3 bucket for the source artifact is created by the pipelinestack.

**Comment by v-karbovnichy** [comment]
@leavertj could you please have a look?

**Comment by aijunpeng** [comment]
Hey there, the error is because the solution template can't find the source code packages needed for creating lambda function from your distribution s3 bucket. In readme,  step 4 and 6 have instructions about how to create s3 buckets and upload deployment assets to the buckets. Please verify if those s3 buckets exist in your AWS account and if all deployment assets are in the buckets. The assets in bucket should be publicly accessible. One more note: make sure you add region as suffix to your distribution bucket name. Here is an example bucket name: my-dist-bucket-us-east-1. Hope this helps. Thanks!

**Comment by abbathaw** [comment]
I have the same issue. I have checked that my bucket includes the region suffix (us-east-1) and also checked that the assets exist and the whole bucket is public.

**Comment by aijunpeng** [comment]
Hey abbathaw, can you please provide a screenshot of your error message and your s3 bucket (redact any sensitive content)? Also are you able to download your assets using the s3 path to your assets https://...?

**Comment by v-karbovnichy** [comment]
I followed these steps to make objects public in both buckets. The error is the same.
![image](https://user-images.githubusercontent.com/7301634/119370919-e9fab400-bcc6-11eb-9529-90248cfc2d6c.png)

These are the results of making bucket contents public:
![image](https://user-images.githubusercontent.com/7301634/119370999-01d23800-bcc7-11eb-984f-44eb84e8e20c.png)
![image](https://user-images.githubusercontent.com/7301634/119371108-1f070680-bcc7-11eb-9371-30b24507489a.png)

**Comment by aijunpeng** [comment]
Thanks for providing the information. What's your bucket level permission? Your bucket should either open to public or have a bucket policy to grant access at bucket level. You can test it out by downloading your assets using the s3 object url ( https://...).

**Comment by kstro21** [comment]
Same issue here, but it has nothing to do with the bucket policy, it is a misleading example in the readme. If we check the templates in the repo we can see this in the Mappings `KeyPrefix: '%SOLUTION_NAME%/%VERSION%'` so the correct example in the readme should be using the env var `$SOLUTION_NAME` and not the hardcoded value of `aws-waf-security-automations`.

Using this deploy successfully

```bash
aws s3 cp ./deployment/regional-s3-assets s3://$DIST_OUTPUT_BUCKET-$AWS_REGION/$SOLUTION_NAME/$VERSION \
--recursive --acl bucket-owner-full-control
```

**Comment by aijunpeng** [comment]
Thanks for the feedback. Solution name is your choice and the readme only provides an example. We will take a look and see if the readme needs to be more clear.
