### ISSUE TITLE
Need Guidance on If this Code support on Node.js 12.X/14.X

### ISSUE THREAD

**Issue by Vinod-Gopinwar** [aws-solutions/aws-waf-security-automations#190]
I have deployed AWS WAF using Cloud Formation. It has Lambda "ReputationListsParser" which is working fine with runtime Node.js 10.X

But as AWS ending support and security patches for Node.js 10.X, I need to upgrade the Node runtime to Node.js 12/14. However I didn't see any documentation which states that this code supports Node.js runtime later version than 10.X.

As WAF deployed in production, I can't just change runtime of Lambda function.

**Describe the feature you'd like**
I will be so helpful if this code is tested with Node.js later versions - 12.X or 14.X and make available its support findings.
Further if you do changes to the code to support Node.js 12.X or 14.X, will be a big help.

**Comment by aijunpeng** [comment]
Thanks for your comment. It seems you are using a version 2.x WAF solution. Starting from v3.0, we have converted ReputationListsParser from NodeJS to Python to make it consistent with the rest of the source code in the solution. We recommend you to upgrade your solution to the latest 3.x, which also supports WAFv2 APIs.
