### ISSUE TITLE
Honeypot  Cloudfront integration

### ISSUE THREAD

**Issue by pbalajiips** [aws-solutions/aws-waf-security-automations#204]
I have deployed "aws-waf-security-automations" Cloudformation template on our stg env. i see the  HoneyPot APIGateway created. to Add CloudFront behavior, if someone has list of honeypot URI please share with me.

**Comment by aijunpeng** [comment]
Thanks for the question. You can find the honeypot URL on the Outputs tab of the CloudFormation stack: open the AWS CloudFormation console, choose the stack that you deployed, choose the Outputs tab, and then choose the value for BadBotHoneypotEndpoint.

**Comment by pbalajiips** [comment]
@aijunpeng Thanks for the response, i was asking about,  list of vulnerable URI that can be monitored by Honeypot, such as
https://www.example.com/.git
https://www.example.com/admin

**Comment by aijunpeng** [comment]
We don't maintain such list. In general, Honeypot can lure and deflect any attackers attempting to access it.
