### ISSUE TITLE
Activate Known bad inputs managed rule group

### ISSUE THREAD

**Issue by lcoelho88** [aws-solutions/aws-waf-security-automations#209]
**Is your feature request related to a problem? Please describe.**
After launch the stack, with the option "Activate AWS Managed Rules" set to yes, it was noticed that it only activates "Core rule set" as AWS managed rule groups which seems incomplete, considering Critical vulnerability with log4j2, for example.

**Describe the feature you'd like**
It would be good to activate, by default, not only "Core rule set" but also **"Known bad inputs"**. Can you please evaluate if it is a good improvement set this as default or, at least, allow the possibility to activate it?

**Additional context**
N/A

**Comment by aijunpeng** [comment]
Thanks for the comment. We will add this to our backlog to be evaluated for future releases.

**Comment by aijunpeng** [comment]
This issue has been addressed in version >=4.0.0.
