### ISSUE TITLE
resource types are not supported for resource import - drift detection operations (us-west-2)

### ISSUE THREAD

**Issue by nevetS** [aws-solutions/aws-waf-security-automations#226]
**Describe the bug**
When creating a CloudFormation Stack, using `aws-waf-security-automation.template`, in the `us-west-2` region, I see the following error:

```
The following resource types are not supported for resource import: Custom::ConfigureAppAccessLogBucket,AWS::Lambda::Permission,Custom::CheckRequirements,Custom::GenerateAppLogParserConfFile,Custom::CreateGlueDatabaseName,Custom::CreateDeliveryStreamName,Custom::CreateUUID,AWS::CloudWatch::Dashboard,AWS::S3::BucketPolicy,Custom::ConfigureWebAcl,Custom::GenerateWafLogParserConfFile,Custom::ConfigureWafLogBucket,Custom::AddAthenaPartitions,Custom::ConfigureAWSWAFLogs,AWS::IAM::Policy,AWS::SNS::TopicPolicy,AWS::SNS::Subscription,Custom::UpdateReputationLists,AWS::Lambda::Permission,AWS::Lambda::Permission,AWS::Lambda::Permission,AWS::Lambda::Permission,AWS::Lambda::Permission,AWS::Lambda::Permission,AWS::Lambda::Permission
```
The learn more link points to this page:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html?icmpid=docs_cfn_console

**To Reproduce**
* clone repo
* build default stack
* upload to s3
* go to cloudformation, create stack, add URL for  `aws-waf-security-automation.template`

**Expected behavior**
Cloudformation stack should be created

**Please complete the following information about the solution:**
- [ ] Version: 3.2.1

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "AWS WAF Security Automations v3.1: This AWS CloudFormation template helps you provision the AWS WAF Security Automations stack without worrying about creating and configuring the underlying AWS infrastructure". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      TemplateBucket: 'solutions-reference'
      SourceBucket: 'solutions'
      KeyPrefix: 'waf-security-automation/v3.1'
```

- [ ] Region: us-west-2
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? yes
- [ ] Were there any errors in the CloudWatch Logs? No

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by aijunpeng** [comment]
Thanks for reporting the issue. Creating stack shouldn't throw those errors. Are you importing resources from the WAF stack into another stack? Please provide more details on how you build and deploy the stack. Screenshots are helpful too. Also if you just want to deploy the default stack, you can follow the implementation guide to deploy the solution's out-of-box stack.

https://docs.aws.amazon.com/solutions/latest/security-automations-for-aws-waf/step1.html

**Comment by aijunpeng** [comment]
close the issue due to inactivity
