### ISSUE TITLE
Incompatible request with urllib3>2

### ISSUE THREAD

**Issue by NicoForce** [aws-solutions/aws-waf-security-automations#239]
**Describe the bug**
Custom Resource lambda gets stuck on creation and is unable to run due to an incompatibility between requests and urllib3. For some reason pip is installing urllib3>2 by default, I had to add urllib3<2 on every requirements.txt so WAF deployment would work.

**To Reproduce**
Deploying the base stack triggers the issue.

**Expected behavior**
Cloudformation deployment happens without hanging and failing.

**Please complete the following information about the solution:**
- [ ] Version: v3.2.5

- [ ] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository? Nope
- [ ] Were there any errors in the CloudWatch Logs? Yes

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'helper': urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips  26 Jan 2017. See: https://github.com/urllib3/urllib3/issues/2168Traceback (most recent call last): | [ERROR] Runtime.ImportModuleError: Unable to import module 'helper': urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips 26 Jan 2017. See: https://github.com/urllib3/urllib3/issues/2168 Traceback (most recent call last):
```

**Comment by WillAWS** [comment]
Just to follow up for more context: are you deploying out of the box or are you building your own custom solution locally and then deploying? A few suggestions: try upgrading to latest Security Automations for WAF (v4.0.1) and see if that fixes your issue. If you are building locally are you tied to your openssl version? Can you bump it to a compatible version that satisfies the correlating urlib3 version?
