### ISSUE TITLE
while build i get No module named 'lib.cw_metrics_util'

### ISSUE THREAD

**Issue by jegjeyam** [aws-solutions/aws-waf-security-automations#243]
____________________________________________________________________________________________________________________ ERROR collecting test/test_access_handler.py ___________________________________________________________________________________________________________________________
ImportError while importing test module '/private/tmp/aws-waf-security-automations/source/access_handler/test/test_access_handler.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_access_handler.py:16: in <module>
    from access_handler.access_handler import *
access_handler.py:21: in <module>
    from lib.cw_metrics_util import WAFCloudWatchMetrics
E   ModuleNotFoundError: No module named 'lib.cw_metrics_util'

**Comment by naruhide** [comment]
Version: v4.0.0

As far as the code of deployment/build-s3-dist.sh is concerned, the following modules are not found either.

```
source/lib/cw_metrics_util.py
source/lib/logging_util.py
source/lib/s3_util.py
source/lib/cfn_response.py
```

**Comment by naruhide** [comment]
Those modules don't seem to exist in v4.0.0.
So it won't work properly.

**Comment by knihit** [comment]
Release v4.0.1 fixes the issue.
