### ISSUE TITLE
Runtime.ImportModuleError: Unable to import module 'helper': No module named 'lib.s3_util'

### ISSUE THREAD

**Issue by patrickmagyarskaylink** [aws-solutions/aws-waf-security-automations#245]
Hello,

**Describe the bug**
helper Lambda function log output:
`[ERROR] Runtime.ImportModuleError: Unable to import module 'helper': No module named 'lib.s3_util'
Traceback (most recent call last):`

In Line https://github.com/aws-solutions/aws-waf-security-automations/blob/main/deployment/build-s3-dist.sh#L148 the file s3_util.py should copied to the helper lib folder but the file is not in die source directory:
https://github.com/aws-solutions/aws-waf-security-automations/tree/main/source/lib
There are some other files too, which should be copied but not available in the directory. Please check them too.

stack_requirements.py want to use this lib:
https://github.com/aws-solutions/aws-waf-security-automations/blob/main/source/helper/stack_requirements.py#L19

**To Reproduce**
Error occurs during stack creation

**Expected behavior**
- file should be available
- not module error 

**Please complete the following information about the solution:**
- Version: v4.0.0

**Screenshots**
/
**Additional context**
/

**Comment by knihit** [comment]
Release v4.0.1 fixes the issue.
