### ISSUE TITLE
Need help writing Custom ACL 

### ISSUE THREAD

**Issue by sam-germany** [aws-solutions/aws-waf-security-automations#247]
I am trying to write a custom ACL rule based on JWT token come in the request so that i WAF allow or block the request after decoding it. Somehow not able to find the correct way to do it. Can anyone help me sending any example code ?

OR my question in another way, Are we alloweed to write own custom ACL in python and deploy directly with thsi solution ?

**Comment by WillAWS** [comment]
Yes. You are allowed to write your own custom ACL & deploy directly :) Because this is open source, feel free to tweak it to make it work for you.

**Comment by sam-germany** [comment]
From last three-four days i am trying to write custom ACL in python. As i do not find any documentation about how to wirte a custom ACL in python that will be triggered with every request so that i can check the TOKEN come with every request HEADER and write my usecase to allow or block the request. Can you help me with step-by-step guide how to wirte  custome ACL, it will be really helpfull to us for developing the WAF as per our requirements.

**Comment by aijunpeng** [comment]
Unfortunately that is not in the scope of the WAF security automation solution. I would suggest you to check with the Go SDK team or WAF service team on this: https://docs.aws.amazon.com/awssupport/latest/user/case-management.html Thanks!
