### ISSUE TITLE
4.0.2 helper.zip not available in cn-north-1

### ISSUE THREAD

**Issue by mengchen-tam** [aws-solutions/aws-waf-security-automations#251]
**Describe the bug**
Hi, I am trying the solution in CN region. It was working for 4.0.1. 
When using 4.0.2 template(downloaded from solution page), met the error that helper.zip not available in cn-north-1 so the stack cannot be created

**To Reproduce**
Remove AppRegistry code and launch the stack in CN region

**Expected behavior**
Events:
Logical ID: Helper
Status: CREATE_FAILED
Status reason: 
Resource handler returned message: "Your access has been denied by S3, please make sure your request credentials have permission to GetObject for solutions-cn-north-1/security-automations-for-aws-waf/v4.0.2/helper.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied

**Please complete the following information about the solution:**
- [ v4.0.2] Version: 

- [cn-north-1 ] Region: 
- [yes ] Was the solution modified from the version published on this repository? 
- [ no ] If the answer to the previous question was yes, are the changes available on GitHub?
- [yes ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [no ] Were there any errors in the CloudWatch Logs?

**Screenshots**
N/A
**Additional context**
N/A

**Comment by WillAWS** [comment]
Hi, this WAF solution is not supported in China region. However, there is another waf solution supported in China: https://www.amazonaws.cn/en/solutions/amazon-waf-security-automations/. I would recommend you to try that out. Thank you!
