### ISSUE TITLE
Regional bucket requirement does not allow for multiple regions

### ISSUE THREAD

**Issue by LewS** [aws-solutions/aws-waf-security-automations#269]
Per the README Instructions
One regional bucket for each AWS Region where you plan to deploy the solution. Use the name of the global bucket as the prefix of the bucket name, and suffix it with the region name. Regional assets such as Lambda code are stored here. For example, mybucket-us-east-1. 
However when you build the solution using build-s3-dist.sh it only accepts one parameter for DIST_OUTPUT_BUCKET that is required for regional deployment, which is also referenced in the global template under mappings at line 693 SourceBucket: '%DIST_OUTPUT_BUCKET%'.
How can this solution be deployed to multiple regions without overwriting the global templates within the TEMPLATE_OUTPUT_BUCKET each time...

**Comment by LewS** [comment]
I see that the region is appended deeper down

**Comment by kroeter** [comment]
Thank you, we will add for our next release
