### ISSUE TITLE
WAFStaleDataException error with 2.3.0

### ISSUE THREAD

**Issue by darrenweiner1** [aws-solutions/aws-waf-security-automations#85]
Hi there,
Is there a known issue with 2.3.0 and intermittent failures related to this?  It looks like maybe multiple rules are trying to be created at once and this error is being thrown (along with Throttling Exception errors).  If so, any workaround available on this (e.g. is there a specific rule that should be disabled?).
Thanks.

**Comment by sushilfirminiq** [comment]
Facing the same issue while creating the WAF from cloudformation.
Error: "Failed to create resource. An error occurred (WAFStaleDataException) when calling the UpdateWebACL operation: The input token is no longer current"

**Comment by hvital** [comment]
In version 2.3.0 we're leveraging [SDK exponential backoff](https://docs.aws.amazon.com/general/latest/gr/api-retries.html) handler. 

However, depending on how frequent AWS WAF API is called, it might throw this WAFStaleDataException ... This sometimes happen during provisioning/deleting the stack. 

We're working on to also retry call in case of this client error code (WAFStaleDataException). For python lambdas, we can use https://pypi.org/project/backoff/ for that.

**Comment by jeffneuen** [comment]
Are there any suggested workarounds before the next release? This bug is preventing deployment of 2.3.0 via cloudformation in some cases.

**Comment by tomotway** [comment]
Hi, so I'm hitting this issue every time.  Please correct me if I'm wrong but this version appears to be unusable?  Are there any workarounds?  thanks

**Comment by chris-denglere** [comment]
I contacted AWS support about this issue and was told the current workaround is to wait an hour and then try deploying the stack again. It's not the most convenient workaround, but in my experience it does work 100% of the time that I tried it.

**Comment by tomotway** [comment]
I actually tried it about 4 times yesterday and once today and then gave up.   However, based on your comment @chris-denglere I just gave it one more go and it worked, thanks!

**Comment by aijunpeng** [comment]
We have deprecated version 2.3.0. closing the ticket
