### ISSUE TITLE
Feature Request - Geo Match Condition support

### ISSUE THREAD

**Issue by djbrightman** [aws-solutions/aws-waf-security-automations#93]
Would it be possible (or make sense?) to include rule using Geo Match Condition?
e.g. Allow user to enable access from only specified countries

i.e. if no countries specified allow any, if list of countries defined create geo match conditions for those countries and a rule that will allow only access from those meeting the geo match conditions and deny all others

Use case might be for country specific government or public sector applications

**Comment by dscpinheiro** [comment]
Hi @djbrightman,

Sorry for the delay in the response.
We've added your feature request to the backlog for the solution.

**Comment by omartinex** [comment]
Hi @dscpinheiro 

Do you guys have any update on this topic?

Regards

**Comment by aijunpeng** [comment]
This is on our backlog but not prioritized yet.

**Comment by omartinex** [comment]
Hello @aijunpeng thank you very much for your answer,

**Comment by rakshb** [comment]
We recently released an update to the solution (4.0.0+), which supports country and URI configurations in HTTP Flood Athena log parser rule. Let me know if this addresses your request. Thanks!
