### ISSUE TITLE
Issue with s3 image Uploader using image location with chunking.

### ISSUE THREAD

**Issue by DharmeshMertwal** [aws-solutions/aws-waf-security-automations#94]

**Comment by beomseoklee** [comment]
Hi @DharmeshMertwal, can you describe the issue in detail?

**Comment by DharmeshMertwal** [comment]
I am trying to upload image using chunking to S3 and i have activated WAF on my application.
If i am directly upload from my system it will working fine no error occurred during upload if i am trying to save image from any url then i am not able to save image on my s3.

**Comment by beomseoklee** [comment]
Hi @DharmeshMertwal, and thanks for coming back.

To clarify your issue,
1) do you use AWS WAF Security Automation solution or you are using just AWS WAF?
2) how do you upload your image? Do you use API on your system to upload image or directly save your image to S3 using API? It sounds like you are facing CORS problem, so I want to know some details.

**Comment by aijunpeng** [comment]
Closing the old ticket due to inactivity
