### ISSUE TITLE
Wildcard uriList

### ISSUE THREAD

**Issue by tkd4444** [aws-solutions/aws-waf-security-automations#96]
Hello,

Couldn't find it in the documentation so I'm writing here.
Is there a way to use wildcards in the uriList ?

e.g.:

    "*/some_code.js": {
      "requestThreshold": 20,
      "blockPeriod": 5
    }

Thanks !

**Comment by aijunpeng** [comment]
Closing the old ticket due to inactivity. Feel free to open a new one if needed.
