### ISSUE TITLE
need your help regarding WAF

### ISSUE THREAD

**Issue by bipingagan** [aws-solutions/aws-waf-security-automations#98]
Hello,

I need to set in waf, if the 1000 request come in 15 minute per IP address, waf block the ip

I have configured WAF with cloudfarmation its working fine but the time is 1 min to count the request I need to set it 15 min 

Could you please advise any Help URl

**Comment by winem** [comment]
I actually wanted to say that I have an idea how to do that and wanted to provide a PR but a look at the code tells me that it might be even easier. I don't use the plugin but check Athena for a query called 'logParserQuery'. I guess that one contains the limitation to get the events for the last minute (60 seconds) only. 

It should (/may, as I'm not able to reproduce and test it) work to just increase the value here.

**Comment by aijunpeng** [comment]
closing the old ticket due to inactivity
